<a href="https://colab.research.google.com/github/mrosedata/FTW_/blob/main/9_23_2023_PM_Group_5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the relevant libraries
import pandas as pd
import re #regex
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
#importing the dataset and creating a copy for comparison later
df0 = pd.read_csv("DATADROP 2021_V0.csv")
df = df0.copy()

In [ ]:
#display first 5 row
df.head()

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,C404174,38.0,35 to 39,FEMALE,NaN,01/30/2020,01/30/2020,NaN,NaN,RECOVERED,...,NEGROS ORIENTAL,DUMAGUETE CITY (CAPITAL),PH074610000,NaN,NaN,RECOVERED,NO,01/21/2020,NO,"Removal Type is ""Recovered"", but no Recovered ..."
1,C462688,44.0,40 to 44,MALE,NaN,01/30/2020,02/03/2020,02/01/2020,NaN,DIED,...,NEGROS ORIENTAL,DUMAGUETE CITY (CAPITAL),PH074610000,NaN,NaN,DIED,NO,01/18/2020,NaN,NaN
2,C387710,60.0,60 to 64,FEMALE,01/23/2020,01/30/2020,02/05/2020,NaN,01/31/2020,RECOVERED,...,BOHOL,PANGLAO,PH071233000,NaN,NaN,RECOVERED,NO,01/21/2020,NO,Case has Admitting Facility but is not Admitte...
3,C498051,63.0,60 to 64,MALE,03/05/2020,NaN,03/06/2020,03/11/2020,NaN,DIED,...,RIZAL,CAINTA,PH045805000,NaN,NaN,DIED,NO,NaN,NaN,"Case has Lab Result, but Result Date is blank"
4,C377460,49.0,45 to 49,MALE,NaN,NaN,03/06/2020,NaN,NaN,RECOVERED,...,BATANGAS,SANTO TOMAS,PH041028000,NaN,NaN,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."

In [ ]:
#to find out how many rows and columns in the dataset
df.shape

(14225, 22)

In [ ]:
#to find any null values in the dataset
df.isnull().sum()

CaseCode                 0
Age                     51
AgeGroup                51
Sex                      0
DateSpecimen          5388
DateResultRelease     7844
DateRepConf              0
DateDied             12942
DateRecover           7309
RemovalType             45
Admitted              4700
RegionRes               36
ProvRes                809
CityMunRes            1009
CityMuniPSGC          1009
BarangayRes          14225
BarangayPSGC         14225
HealthStatus             1
Quarantined              1
DateOnset             6377
Pregnanttab           7748
ValidationStatus      3770
dtype: int64

In [ ]:
#Detect existing non-missing values
df.notna().sum()

CaseCode             14225
Age                  14174
AgeGroup             14174
Sex                  14225
DateSpecimen          8837
DateResultRelease     6381
DateRepConf          14225
DateDied              1283
DateRecover           6916
RemovalType          14180
Admitted              9525
RegionRes            14189
ProvRes              13416
CityMunRes           13216
CityMuniPSGC         13216
BarangayRes              0
BarangayPSGC             0
HealthStatus         14224
Quarantined          14224
DateOnset             7848
Pregnanttab           6477
ValidationStatus     10455
dtype: int64